### ISSUE TITLE
AttributeError: While running notebook "AU_Mic_illustrate_flares_FIGURE1.ipynb"

### ISSUE THREAD

**Issue by rajph0** [ekaterinailin/flaring-spi#1]
While trying to run the code: **"flcc, ax = custom_detrending(lc, spline_order=3, spline_coarseness=6,  max_sigma=1.5)"** from the provided notebook"AU_Mic_illustrate_flares_FIGURE1.ipynb", I am getting an error like **"AttributeError: Table' object has no attribute 'time'.**
The lc file is attached herewith.
![flaring_spi_lc](https://user-images.githubusercontent.com/113608226/220535365-083db541-fe36-4059-9cb0-b10cd824a0eb.png)

The error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[14], line 2
      1 get_ipython().run_line_magic('matplotlib', 'inline')
----> 2 flcc, ax = custom_detrending(lc, spline_order=3, spline_coarseness=6,  max_sigma=1.5)

File ~/flaring-spi-master/notebooks/funcs/detrend.py:59, in custom_detrending(lc, spline_coarseness, spline_order, savgol1, savgol2, pad, max_sigma, longdecay)
     23 def custom_detrending(lc, spline_coarseness=30, spline_order=3,
     24                       savgol1=6., savgol2=3., pad=3, max_sigma=2.5, 
     25                       longdecay=6,):
     26     """Custom de-trending for TESS and Kepler 
     27     short cadence light curves, including TESS Cycle 3 20s
     28     cadence.
   (...)
     57     FlareLightCurve with detrended_flux attribute
     58     """
---> 59     dt = np.mean(np.diff(lc.time.value))
     61     # fit a spline to the general trends
     62     lc1, model = fit_spline(lc, spline_order=spline_order,
     63                             spline_coarseness=spline_coarseness)

AttributeError: 'Table' object has no attribute 'time'

**Comment by ekaterinailin** [comment]
This is a problem with AltaiPony. You can solve it by uninstalling AltaiPony and cloning and installing from source the latest version of the software like so:

```
git clone https://github.com/ekaterinailin/AltaiPony.git
cd AltaiPony
python setup.py install
```
